recipe_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import login_view, logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from .views import welcome
from .views import RecipeListView
from .views import RecipeDetailView
from .views import records

app_name = 'recipes'

urlpatterns = [
    path('', welcome, name='home'),
    path('list/', RecipeListView.as_view(), name='list'),
    path('list/<pk>', RecipeDetailView.as_view(), name='detail'),
    path('search/', records, name='search'),
]

recipes/models.py
from django.db import models
from django.shortcuts import reverse

# Create your models here.


class Recipe (models.Model):
    name = models.CharField(max_length=120)
    cooking_time = models.FloatField(help_text='in minutes')
    ingredients = models.CharField(max_length=350)
    description = models.TextField()
    pic = models.ImageField(upload_to='recipes', default='no_image.svg')

    # calculate difficulty of recipe using cooking time and number of ingredients
    def calculate_difficulty(self):
        ingredients = self.ingredients.split(', ')
        if self.cooking_time < 30 and len(ingredients) < 7:
            difficulty = 'Easy'
        elif self.cooking_time < 30 and len(ingredients) >= 7:
            difficulty = 'Medium'
        elif self.cooking_time >= 30 and len(ingredients) < 7:
            difficulty = 'Intermediate'
        elif self.cooking_time >= 30 and len(ingredients) >= 7:
            difficulty = 'Hard'
        return difficulty

    def get_absolute_url(self):
        return reverse('recipes:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return str(self.name)

users/models.py
from django.db import models

# Create your models here.


class User(models.Model):
    name = models.CharField(max_length=120)

    def __str__(self):
        return str(self.name)

recipes/forms.py
from django import forms


CHART__CHOICES = (
    ('#1', 'Bar chart'),
    ('#2', 'Pie chart'),
    ('#3', 'Line chart')
)

DIFFIC__CHOICES = (
    ('#1', 'Easy'),
    ('#2', 'Medium'),
    ('#3', 'Intermediate'),
    ('#4', 'Hard')
)


class RecipesSearchForm(forms.Form):
    recipe_diff = forms.ChoiceField(choices=DIFFIC__CHOICES)
    chart_type = forms.ChoiceField(choices=CHART__CHOICES)

recipe_project/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm


def login_view(request):
    error_message = None
    form = AuthenticationForm()

    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)

        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')

            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('/list')
        else:
            error_message = 'Oops.. Something went wrong!'

    context = {
        'form': form,
        'error_message': error_message
    }
    return render(request, 'auth/login.html', context)


def logout_view(request):
    logout(request)
    return render(request, 'auth/success.html')

recipes/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Recipe
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

from .forms import RecipesSearchForm
import pandas as pd
from .utils import get_recipename_from_id, get_chart

# Create your views here.


def welcome(request):
    return render(request, 'recipes/recipes_home.html')


class RecipeListView(LoginRequiredMixin, ListView):
    model = Recipe
    template_name = 'recipes/main.html'


class RecipeDetailView(LoginRequiredMixin, DetailView):
    model = Recipe
    template_name = 'recipes/detail.html'


@login_required
def records(request):
    form = RecipesSearchForm(request.POST or None)
    recipe_df = None
    recipe_diff = None
    chart = None
    qs = None
    if request.method == 'POST':
        recipe_diff = request.POST.get('recipe_diff')
        chart_type = request.POST.get('chart_type')

        if recipe_diff == '#1':
            recipe_diff = 'Easy'
        if recipe_diff == '#2':
            recipe_diff = 'Medium'
        if recipe_diff == '#3':
            recipe_diff = 'Intermediate'
        if recipe_diff == '#4':
            recipe_diff = 'Hard'

        qs = Recipe.objects.all()
        id_searched = []
        for obj in qs:
            diff = obj.calculate_difficulty()
            if diff == recipe_diff:
                id_searched.append(obj.id)

        qs = qs.filter(id__in=id_searched)

        if qs:
            recipe_df = pd.DataFrame(qs.values())
            chart = get_chart(chart_type, recipe_df,
                              labels=recipe_df['name'].values)

            recipe_df = recipe_df.to_html()

    context = {
        'form': form,
        'recipe_df': recipe_df,
        'recipe_diff': recipe_diff,
        'chart': chart,
        'qs': qs,
    }

    return render(request, 'recipes/search.html', context)

users/views.py
from django.shortcuts import render

# Create your views here.

recipes/templates/recipes/detail.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <title>RecipeApp Details</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="{% static 'recipes/images/favicon.png' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'recipes/css/styles.css' %}">
    <style type="text/css">
        body {
            background: url("{% static 'recipes/images/home_background.jpg' %}") no-repeat fixed;
            background-size: cover;
        }
    </style>
</head>

<div class="details_modal">
    <h2>Details: {{object.name}}</h2>
    <div class="details_body">
        <div class="details_short">
            <b>Name: </b> {{object.name}} <br>
            <b>Cooking Time (min): </b> {{object.cooking_time}} <br>
            <b>Difficulty: </b> {{object.calculate_difficulty}} <br><br>
            <img class="food_images" src="{{object.pic.url}}" />
        </div>

        <div class="details_long">
            <b>Ingredients: </b> {{object.ingredients}} <br><br>
            <b>Description: </b> {{object.description}} <br><br>
            <button onclick="goBack()" class="login_btn">Back</button>
        </div>
    </div>
</div>
<script>
    function goBack() {
        window.history.back();
    }
</script>

</html>

recipes/templates/recipes/main.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>RecipeApp Recipes</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <link rel="shortcut icon" href="{% static 'recipes/images/favicon.png' %}">
    <link rel='stylesheet' type='text/css' href="{% static 'recipes/css/styles.css' %}">
    <style type="text/css">
        body {
            background: url("{% static 'recipes/images/home_background.jpg' %}") no-repeat fixed;
            background-size: cover;
        }
    </style>
</head>

<body>
    <div class="nav-bar">
        <img id="logo" src="{% static 'recipes/images/logo.png' %}" height="100px" width="150px">
        <div class="search_box">
            <form action="" method="GET" class="form">
                {% csrf_token %}
                <input type="text" name="recipe_search" class="form_search_input" id="searchbar"
                    placeholder="Search Recipes" onkeyup="search_recipe()" />
            </form>
            <br>
            <div class="search_results" autocomplete="off" style="display: none;">
                {% for object in object_list %}
                <p class="recipe_searched">
                    <a class="recipe_name"
                        style="font-size: 18px; font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;"
                        href="{{object.get_absolute_url}}"> {{object.name}} </a>
                </p>
                {% endfor %}
            </div>
        </div>
        <div>
            <a href="{%url 'recipes:search' %}" class="logout_btn">Display Recipe Data</a>
        </div>
        <div>
            <a href="{%url 'logout' %}" class="logout_btn">Logout</a>
        </div>
    </div>

    <div class="recipe_grid">
        {% for object in object_list %}
        <div class="grid_item">
            <h4><a class="recipe_name" href="{{object.get_absolute_url}}"> {{object.name}} </a></h4>
            <div style="margin-bottom: 10px;">
                <b>Cooking Time: </b> {{object.cooking_time}} <br>
                <b>Difficulty: </b> {{object.calculate_difficulty}} <br>
            </div>
            <img class="food_images" src="{{object.pic.url}}" />
        </div>
        {% endfor %}
    </div>
    <!-- <a href="{%url 'recipes:search' %}" style="
        color: white; 
        background-color: rgba(0, 0, 0, 0.704); 
        border-radius: 8px; 
        padding: 7px;
        text-decoration: none;">
        Search Recipe Data
    </a> -->
    <script src="{% static 'recipes/js/js.js' %}"></script>
</body>

</html>

recipes/templates/recipes/recipes_home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>RecipeApp Home</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <link rel="shortcut icon" href="{% static 'recipes/images/favicon.png' %}">
    <link rel='stylesheet' type='text/css' href="{% static 'recipes/css/styles.css' %}">
    <style type="text/css">
        body {
            background: url("{% static 'recipes/images/home_background.jpg' %}") no-repeat fixed;
            background-size: cover;
            display: flex;
            flex-direction: column;
            align-items: center;
            margin-top: 30vh;
        }

        h1,
        h3 {
            color: rgb(7, 120, 90);
            font-family: 'Roboto Mono', 'Calibri', 'Trebuchet MS', sans-serif;
        }

        img {
            border-radius: 15px;
        }
    </style>
</head>

<body>
    <img src="{% static 'recipes/images/logo.png' %}" width="300px">
    <h1>Welcome to My Recipe App</h1>
    <h3>Log in to your account to see our list of recipes</h3>
    <a href="{%url 'login' %}" class="login_btn"> Login </a>
</body>

</html>

recipes/templates/recipes/search.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>RecipeApp Search</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <link rel="shortcut icon" href="{% static 'recipes/images/favicon.png' %}">
    <link rel='stylesheet' type='text/css' href="{% static 'recipes/css/styles.css' %}">
    <style type="text/css">
        body {
            background: url("{% static 'recipes/images/home_background.jpg' %}") no-repeat fixed;
            background-size: cover;
            color: black;
            display: flex;
            flex-direction: column;
            align-items: center;
            font-family: 'Roboto Mono', 'Calibri', 'Trebuchet MS', sans-serif;
        }

        .form_data {
            background-color: rgba(0, 0, 0, 0.61);
            border-radius: 10px;
            padding: 20px;
        }
    </style>
</head>

<h1 style="font-size: 45px">Search for recipes in our database</h1>
<hr>
<form action="" method="POST" class="form_data">
    {% csrf_token %}
    {{form}}
    <button type="submit">Search</button>

</form>
<br>
<br>
{% if recipe_df %}
{{recipe_df|safe}}
<br>
<img alt='chart' src="data:image/png;base64, {{chart|safe}}">
{% else %}
<h3> no data</h3>
{% endif %}

<br>
<button onclick="goBack()" class="login_btn">Back</button>

<script>
    function goBack() {
        window.history.back();
    }
</script>

</html>